DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nick TEXT NOT NULL,
    tytul TEXT NOT NULL,
    text TEXT NOT NULL
);